### PR TITLE
Architecture

### PR DESCRIPTION
**Pull request by emmagan**

### CODE REVIEW

**Review by DelineoModeling — APPROVED** [review]
Good to go

**Review by agelas — APPROVED** [review]
Should be a passing build lol

**Review by migboko1 — APPROVED** [review]

**Review by VoyagerWSH — APPROVED** [review]
Approved

**Review by clo514 — APPROVED** [review]

**Review by arielbr — APPROVED** [review]

**Review by Ryanqaz123 — COMMENTED** [review]
Architecture merge

**Pull request merged**
